# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Sameer Totey
tagline:          'My personal joural'
description:      'The webhome'
baseurl:          /

author:
  name:           'Sameer Totey'
  url:            http:www.sameertotey.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/sameertotey
